version: "2"

services:

  samba:
    image: dperson/samba
    restart: always
    command: '-u "pi;password" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    ports:
      - 139:139
      - 445:445
    environment:
      - VETO=yes
    volumes:
      - /usr/share/zoneinfo/America/Argentina/Buenos_Aires:/etc/localtime
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads

  plex:
    image: jaymoulin/plex
    expose:
      - 32400
      - 33400
    hostname: raspberrypi
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped
    network_mode: "host"
      #lan:
        #ipv4_address: 192.168.0.3

  transmission:
    image : jaymoulin/transmission
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413/tcp
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    image : pablokbs/docker-flexget:amd64
    volumes:
      - ./flexget:/config
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 5050:5050
    environment:
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=123456
    restart: unless-stopped
    links:
      - transmission

networks:
  lan:
    driver: macvlan
    driver_opts:
      parent: enp0s31f6
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          gateway: "192.168.0.1"
