version: "2"

services:

  samba:
    image: dperson/samba
    restart: always
    command: '-u "pi;password" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    ports:
      - 139:139
      - 445:445
    environment:
      - VETO=yes
    volumes:
      - /usr/share/zoneinfo/America/Argentina/Buenos_Aires:/etc/localtime
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads

  plex:
    image: jaymoulin/plex
    expose:
      - 32400
      - 33400
    hostname: raspberrypi
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped
    # networks:
    #   lan:
    #     ipv4_address: 192.168.1.193
    network_mode: "host"

  # plex_video_converter:
  #   image: jaymoulin/rpi-plex-video-converter
  #   volumes:
  #     - ${MEDIA}:/media
  #   restart: unless-stopped

  # tautulli:
  #   image: linuxserver/tautulli
  #   container_name: tautulli
  #   environment:
  #     - PUID=1001
  #     - PGID=1001
  #     - TZ=America/Argentina/Buenos_Aires
  #   volumes:
  #     - ${STORAGE}/Plex Media Server/tautulli:/config
  #     - ${STORAGE}/Plex Media Server/tautulli-logs:/logs
  #   ports:
  #     - 8181:8181

  transmission:
    image : jaymoulin/transmission
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413/tcp
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    image : cpoppema/docker-flexget
    volumes:
      - ./flexget:/config
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 5050:5050
    environment:
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=123456
    restart: unless-stopped
    links:
      - transmission

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      WEBPASSWORD: 'Q*6ENPS\\;XX3q(-'
    # Volumes store your data between container upgrades
    volumes:
       - ${STORAGE}/etc-pihole/:/etc/pihole/
       - ${STORAGE}/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=America/Argentina/Buenos_Aires
      - SUBDOMAINS=kevinszuchet
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=false #optional
    volumes:
      - ${STORAGE}/duckdns:/config #optional
    restart: unless-stopped

# USING DOCKER MACVLAN NETWORKS: https://blog.oddbit.com/post/2018-03-12-using-docker-macvlan-networks/
# sudo ip link add plex-net link enp0s31f6 type macvlan mode bridge
# sudo ip addr 192.168.1.223/32 dev plex-net
# sudo ip addr add 192.168.1.223/32 dev plex-net
# sudo ip link set plex-net up
# sudo ip link set plex-net up
# sudo ip route add 192.168.1.192/27 dev plex-net

# networks:
#   lan:
#     driver: macvlan
#     driver_opts:
#       parent: enp0s31f6
#     ipam:
#       config:
#         - subnet: "192.168.1.0/24"
#           gateway: "192.168.1.1"
#           ip_range: "192.168.1.192/27"
#           aux_addresses: "host=192.168.1.223"
